apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: qtile-runners
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - name: debug-volume
      mountPath: /opt/hostedtoolcache
    stdin: true
    tty: true
  volumes:
  - name: debug-volume
    persistentVolumeClaim:
      claimName: tool-cache-runnerset
  restartPolicy: Never
