apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: arc-runners
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - name: debug-volume
      mountPath: /mnt/debug
    stdin: true
    tty: true
  volumes:
  - name: debug-volume
    persistentVolumeClaim:
      claimName: tool-cache-runnerset
  restartPolicy: Never
