---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tool-cache-runnerset
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: runnerset
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
